---
new_page_extension: html
auto_deploy: true
admin_path: "/.forestry/"
webhook_url: ''
sections:
- type: directory
  path: src/photo
  label: photo
  create: all
  match: "**/*"
- type: directory
  path: src/blog
  label: blog
  create: all
  match: "**/*"
  new_doc_ext: html .css
upload_dir: src/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
