---
new_page_extension: md
auto_deploy: false
admin_path: https://github.com/oliv66001/eval4.3tentative2-merge
webhook_url: 
sections:
- type: directory
  path: photo-bebe
  label: Photo-bebe
  create: all
  match: bebe
upload_dir: https://github.com/oliv66001/eval4.3tentative2-merge/tree/master/_site/images
public_path: _site
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: https://github.com/oliv66001/eval4.3tentative2-merge/tree/master/_site
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
