---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: photo-couple
  label: photo-couple
  create: all
  match: "**/*"
- type: directory
  path: blog
  label: post
  create: all
  match: post-couple
  exclude: 'tags: couple'
  templates:
  - post-photo-couple
- type: heading
  label: blog
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:, :tags:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
